DomenicoPieShop_Empty/Controllers/PieController.cs
using DomenicoPieShop_Empty.Models;
using DomenicoPieShop_Empty.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DomenicoPieShop_Empty.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository pieRepository;
        private readonly ICategoryRepository categoryRepository;
        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            this.pieRepository = pieRepository;
            this.categoryRepository = categoryRepository;
        }
        //public IActionResult List()
        //{
        //    var viewModel = new PieListViewModel(pieRepository.AllPies, "All Pies");
        //    return View(viewModel);
        //}
        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string? currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PieId);
                currentCategory = categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PieListViewModel(pies, currentCategory));
        }

        public IActionResult Details(int id)
        {

            var pie =  pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie); 
        }
        public IActionResult Search()
        { return View(); }
    }
}

DomenicoPieShop_Empty/Pages/Shared/_PageLayout.cshtml
<!-- questo pezzo di codice è un template che può essere messo in qualsiasi view-->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bethany's Pie Shop</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/popper.js/umd/popper.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    @*Permette di fare validazione lato client*@
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <base href="/" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                 aria-label="Bethany's Pie Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47" class="d-inline-block align-top mb-2 mt-1"
                             alt="Bethany's Pie Shop Logo">
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Pie" asp-action="List" class="nav-link">Pies</a>
                            </li>
                            <li>
                                <vc:category-menu></vc:category-menu>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
                            </li>
                        </ul>

                    </div>

                    <vc:shopping-cart-summary></vc:shopping-cart-summary>
                </div>
            </nav>
        </header>

        @RenderBody()<!-- chiama la view chiamata dal controller-->
    </div>

</body>
</html>
 